-- ==========================================
-- SONEXA LIVE ROOMS REAL-TIME SCHEMA V3
-- ==========================================

-- 1. EXTEND ROOMS TABLE (If needed)
-- Assuming "Rooms" table exists, we ensure we have explicit roles mapping.
-- We will use a dedicated enum for roles if possible, but text is fine.

-- 2. ROOM MESSAGES (Paginated Chat)
CREATE TABLE IF NOT EXISTS public.room_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES public."Rooms"(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL, -- Assuming Users table uses BIGINT or UUID, adjust if needed
    user_name TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT DEFAULT 'text' CHECK (type IN ('text', 'system', 'announcement')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast pagination
CREATE INDEX IF NOT EXISTS idx_room_messages_room_created ON public.room_messages (room_id, created_at DESC);

-- 3. ROOM QUEUE (Expanded Model)
CREATE TABLE IF NOT EXISTS public.room_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES public."Rooms"(id) ON DELETE CASCADE,
    song_uri TEXT NOT NULL,
    song_title TEXT NOT NULL,
    song_artist TEXT NOT NULL,
    song_image TEXT,
    added_by BIGINT NOT NULL,
    state TEXT DEFAULT 'queued' CHECK (state IN ('queued', 'playing', 'played')),
    votes INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_room_queue_room_state ON public.room_queue (room_id, state);

-- 4. ROOM MODERATION & ROLES
CREATE TABLE IF NOT EXISTS public.room_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES public."Rooms"(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    role TEXT DEFAULT 'listener' CHECK (role IN ('host', 'moderator', 'listener')),
    is_muted BOOLEAN DEFAULT FALSE,
    is_banned BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(room_id, user_id)
);

-- 5. ROOM EVENTS (System Activity)
CREATE TABLE IF NOT EXISTS public.room_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID NOT NULL REFERENCES public."Rooms"(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- e.g., 'user_joined', 'song_added', 'room_settings_changed'
    user_name TEXT,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. PLAYER STATE (Synchronised Stream)
-- We store the definitive player state here for late-joiners.
-- Real-time scrubbing is handled by Supabase Broadcasts.
CREATE TABLE IF NOT EXISTS public.player_state (
    room_id UUID PRIMARY KEY REFERENCES public."Rooms"(id) ON DELETE CASCADE,
    current_song_uri TEXT,
    is_playing BOOLEAN DEFAULT FALSE,
    playback_position_ms INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Note: 
-- 1. Emoji Reactions do NOT need a table. They use Supabase Ephemeral Broadcasts.
-- 2. Room Presence does NOT need a table. It uses Supabase Presence.

-- ==========================================
-- ENABLE REALTIME FOR NEW TABLES
-- ==========================================
ALTER PUBLICATION supabase_realtime ADD TABLE public.room_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.room_queue;
ALTER PUBLICATION supabase_realtime ADD TABLE public.room_roles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.room_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.player_state;
